---
resources:
- name: pal-tracker
  type: git
  source:
    uri: {{github-repository}}
    branch: master
    private_key: {{github-private-key}}

- name: pal-tracker-artifacts
  type: s3
  source:
    bucket: {{aws-bucket}}
    regexp: releases/pal-tracker-(.*).jar
    access_key_id: {{aws-access-key-id}}
    secret_access_key: {{aws-secret-access-key}}

- name: version
  type: semver
  source:
    bucket: {{aws-bucket}}
    key: pal-tracker/version
    access_key_id: {{aws-access-key-id}}
    secret_access_key: {{aws-secret-access-key}}

- name: review-deployment
  type: cf
  source:
    api: {{cf-api-url}}
    username: {{cf-username}}
    password: {{cf-password}}
    organization: {{cf-org}}
    space: review

- name: production-deployment
  type: cf
  source:
    api: {{cf-api-url}}
    username: {{cf-username}}
    password: {{cf-password}}
    organization: {{cf-org}}
    space: production

jobs:
- name: build
  plan:
  - get: pal-tracker
    trigger: true
  - get: version
    params: {bump: patch}
  - task: build and test
    file: pal-tracker/ci/build.yml
  - put: pal-tracker-artifacts
    params:
      file: build-output/pal-tracker.jar
  - put: version
    params:
      file: version/number

- name: deploy-review
  plan:
  - get: pal-tracker
    passed: [build]
  - get: pal-tracker-artifacts
    trigger: true
    passed: [build]
  - task: migrate database
    file: pal-tracker/ci/migrateDatabase.yml
    params:
      CF_API_URL: https://api.sys.pikes.pal.pivotal.io
      CF_USERNAME: rmcinerney@pivotal.io
      CF_PASSWORD: e858bdfa
      CF_ORG: rebecca-mcinerney-pal
      CF_SPACE: review
      MYSQL_IP: 192.168.16.87
      DATABASE_NAME: cf_37740baf_3b05_4485_adb2_65500a4f3539
      DATABASE_USERNAME: wjTZzLvL9B29CRsY
      DATABASE_PASSWORD: WwqEEczDuSGWbfGy
  - put: review-deployment
    params:
      manifest: pal-tracker/manifest-review.yml
      path: pal-tracker-artifacts/pal-tracker-*.jar
      environment_variables:
        WELCOME_MESSAGE: "Hello from the review environment"

- name: deploy-production
  plan:
  - get: pal-tracker
    passed: [deploy-review]
  - get: pal-tracker-artifacts
    passed: [deploy-review]
  - task: migrate database
    file: pal-tracker/ci/migrateDatabase.yml
    params:
      CF_API_URL: https://api.sys.pikes.pal.pivotal.io
      CF_USERNAME: rmcinerney@pivotal.io
      CF_PASSWORD: e858bdfa
      CF_ORG: rebecca-mcinerney-pal
      CF_SPACE: production
      MYSQL_IP: 192.168.16.87
      DATABASE_NAME: cf_f51d41e7_ada2_42c6_85ca_9d254cb9be46
      DATABASE_USERNAME: mkRXClES4I4NpF5D
      DATABASE_PASSWORD: IPoX5zr60CFDmSpe
  - put: production-deployment
    params:
      manifest: pal-tracker/manifest-production.yml
      path: pal-tracker-artifacts/pal-tracker-*.jar
      environment_variables:
        WELCOME_MESSAGE: "Hello from the production environment"
